#!/bin/bash
# setup-docker-backup.sh
# Self Hosted Home UK — github.com/SelfHostedHomeUK
#
# Interactive setup for Docker volume and host directory backups.
# Creates a backup script configured for your environment and optionally
# adds a cron job to run it nightly, plus a login message to .bashrc
# showing when the last backup ran.
#
# Usage:
#   chmod +x setup-docker-backup.sh
#   ./setup-docker-backup.sh
#
# Requirements:
#   - Docker installed and running
#   - Backup destination mounted and writable before running
#   - Ubuntu / Debian based system

set -e

echo ""
echo "Docker Volume Backup Setup"
echo "Self Hosted Home UK — selfhostedhome.co.uk"
echo "────────────────────────────────────────────"
echo ""

# ── Backup destination ────────────────────────────────────────────────────────
read -p "Enter the full path to your backup destination (e.g. /mnt/backup or /home/ubuntu/smb-backup): " BACKUP_DIR

if [ -z "$BACKUP_DIR" ]; then
    echo "❌  No backup destination provided. Exiting."
    exit 1
fi

if [ ! -d "$BACKUP_DIR" ]; then
    echo "⚠️  Directory does not exist: $BACKUP_DIR"
    read -p "Create it now? (y/n): " CREATE_DIR
    if [ "$CREATE_DIR" = "y" ]; then
        mkdir -p "$BACKUP_DIR"
        echo "✅  Created: $BACKUP_DIR"
    else
        echo "❌  Backup destination not available. Exiting."
        exit 1
    fi
fi

echo ""

# ── Log file location ─────────────────────────────────────────────────────────
read -p "Enter the full path for the log file [default: /home/ubuntu/backup-docker-volumes.log]: " LOG_FILE
LOG_FILE=${LOG_FILE:-/home/ubuntu/backup-docker-volumes.log}

echo ""

# ── Timestamp file location ───────────────────────────────────────────────────
read -p "Enter the full path for the timestamp file [default: /home/ubuntu/.last_docker_backup]: " TIMESTAMP_FILE
TIMESTAMP_FILE=${TIMESTAMP_FILE:-/home/ubuntu/.last_docker_backup}

echo ""

# ── Retention period ──────────────────────────────────────────────────────────
read -p "How many days of backups to keep? [default: 7]: " RETENTION_DAYS
RETENTION_DAYS=${RETENTION_DAYS:-7}

echo ""

# ── Docker volumes ────────────────────────────────────────────────────────────
echo "Enter the Docker volume names to back up, one per line."
echo "Press Enter on a blank line when done."
echo "(Run 'docker volume ls' to list your volumes)"
echo ""

VOLUMES=()
while true; do
    read -p "  Volume name (or blank to finish): " VOL
    [ -z "$VOL" ] && break
    VOLUMES+=("$VOL")
done

echo ""

# ── Host directories ──────────────────────────────────────────────────────────
echo "Enter the host directories to back up, one per line."
echo "Press Enter on a blank line when done."
echo ""

HOST_DIRS=()
while true; do
    read -p "  Directory path (or blank to finish): " DIR
    [ -z "$DIR" ] && break
    HOST_DIRS+=("$DIR")
done

echo ""

# ── Output script location ────────────────────────────────────────────────────
read -p "Where to save the generated backup script? [default: /home/ubuntu/backup-docker-volumes.sh]: " SCRIPT_PATH
SCRIPT_PATH=${SCRIPT_PATH:-/home/ubuntu/backup-docker-volumes.sh}

echo ""

# ── Summary ───────────────────────────────────────────────────────────────────
echo "Summary:"
echo "  Backup destination : $BACKUP_DIR"
echo "  Log file           : $LOG_FILE"
echo "  Timestamp file     : $TIMESTAMP_FILE"
echo "  Retention          : $RETENTION_DAYS days"
echo "  Docker volumes     : ${#VOLUMES[@]}"
for V in "${VOLUMES[@]}"; do echo "    - $V"; done
echo "  Host directories   : ${#HOST_DIRS[@]}"
for D in "${HOST_DIRS[@]}"; do echo "    - $D"; done
echo "  Script output      : $SCRIPT_PATH"
echo ""
read -p "Proceed? (y/n): " CONFIRM
if [ "$CONFIRM" != "y" ]; then
    echo "Cancelled."
    exit 0
fi

echo ""

# ── Generate the backup script ────────────────────────────────────────────────
cat > "$SCRIPT_PATH" << SCRIPT
#!/bin/bash
# backup-docker-volumes.sh
# Generated by setup-docker-backup.sh — Self Hosted Home UK
# selfhostedhome.co.uk

BACKUP_DIR="$BACKUP_DIR"
LOG_FILE="$LOG_FILE"
DATE=\$(date +%F)
RUN_TIME=\$(date '+%Y-%m-%d %H:%M:%S')

echo "=== Backup started at \$RUN_TIME ===" | tee -a "\$LOG_FILE"

SCRIPT

# Add Docker volume backup blocks
if [ ${#VOLUMES[@]} -gt 0 ]; then
    cat >> "$SCRIPT_PATH" << SCRIPT
# Docker volumes
SCRIPT
    for VOL in "${VOLUMES[@]}"; do
        cat >> "$SCRIPT_PATH" << SCRIPT
echo "Backing up Docker volume $VOL..." | tee -a "\$LOG_FILE"
docker run --rm -v "$VOL:/volume" -v "\$BACKUP_DIR:/backup" alpine \\
    sh -c "cd /volume && tar czf /backup/${VOL}-\${DATE}.tar.gz ." 2>>"\$LOG_FILE"
if [ \$? -eq 0 ]; then
    echo "✅ $VOL backup completed successfully." | tee -a "\$LOG_FILE"
else
    echo "❌ $VOL backup FAILED!" | tee -a "\$LOG_FILE"
fi

SCRIPT
    done
fi

# Add host directory backup blocks
if [ ${#HOST_DIRS[@]} -gt 0 ]; then
    cat >> "$SCRIPT_PATH" << SCRIPT
# Host directories
SCRIPT
    for DIR in "${HOST_DIRS[@]}"; do
        BASENAME=$(basename "$DIR")
        cat >> "$SCRIPT_PATH" << SCRIPT
echo "Backing up host directory $DIR..." | tee -a "\$LOG_FILE"
tar czf "\$BACKUP_DIR/${BASENAME}-\${DATE}.tar.gz" -C "$(dirname "$DIR")" "$BASENAME" 2>>"\$LOG_FILE"
if [ \$? -eq 0 ]; then
    echo "✅ $BASENAME backup completed successfully." | tee -a "\$LOG_FILE"
else
    echo "❌ $BASENAME backup FAILED!" | tee -a "\$LOG_FILE"
fi

SCRIPT
    done
fi

# Add cleanup and completion
cat >> "$SCRIPT_PATH" << SCRIPT
# Remove backups older than $RETENTION_DAYS days
find "\$BACKUP_DIR" -name "*.tar.gz" -type f -mtime +$RETENTION_DAYS -delete

RUN_END=\$(date '+%Y-%m-%d %H:%M:%S')
date '+%Y-%m-%d %H:%M:%S' > $TIMESTAMP_FILE
echo "Backup completed at \$RUN_END" | tee -a "\$LOG_FILE"
echo "===================================" | tee -a "\$LOG_FILE"
SCRIPT

chmod +x "$SCRIPT_PATH"
echo "✅  Backup script created at $SCRIPT_PATH"

# ── Cron job ──────────────────────────────────────────────────────────────────
echo ""
read -p "Add a nightly cron job to run this automatically at 02:00? (y/n): " ADD_CRON
if [ "$ADD_CRON" = "y" ]; then
    CRON_CMD="0 2 * * * bash $SCRIPT_PATH"
    ( crontab -l 2>/dev/null | grep -v "$SCRIPT_PATH"; echo "$CRON_CMD" ) | crontab -
    echo "✅  Cron job added — nightly backup at 02:00"
fi

# ── Bashrc login message ──────────────────────────────────────────────────────
echo ""
read -p "Add a login message to .bashrc showing last backup time? (y/n): " ADD_BASHRC
if [ "$ADD_BASHRC" = "y" ]; then
    if grep -q "last_docker_backup" ~/.bashrc; then
        echo "ℹ️   Bashrc block already present — skipping"
    else
        cat >> ~/.bashrc << BASHRC

# Docker backup monitor — added by setup-docker-backup.sh
if [ -f $TIMESTAMP_FILE ]; then
    last_backup=\$(cat $TIMESTAMP_FILE)
    last_backup_epoch=\$(date -d "\$last_backup" +%s)
    now_epoch=\$(date +%s)
    diff_hours=\$(( (now_epoch - last_backup_epoch) / 3600 ))
    if [ "\$diff_hours" -gt 24 ]; then
        echo "⚠️  Last Docker backup: \$last_backup (\$diff_hours hours ago)"
    else
        echo "✅  Last Docker backup: \$last_backup"
    fi
else
    echo "⚠️  No Docker backup recorded yet"
fi
BASHRC
        echo "✅  Bashrc block added — will show on next SSH login"
    fi
fi

echo ""
echo "────────────────────────────────────────────"
echo "Setup complete."
echo "To test immediately: bash $SCRIPT_PATH"
echo ""
